# PANDAS PRACTICE

In [1]:
#Q1

In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.__version__

'0.24.2'

In [4]:
#Q2

In [5]:
s1=pd.Series([11,22,33,44,55])

In [6]:
s1

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [7]:
arr=np.array([3,2,5,6])

In [8]:
arr

array([3, 2, 5, 6])

In [9]:
s2=pd.Series(arr)

In [10]:
s2

0    3
1    2
2    5
3    6
dtype: int32

In [11]:
d1={"name":"bushra",
   "father name":"afsar"}

In [12]:
d1

{'name': 'bushra', 'father name': 'afsar'}

In [13]:
s3=pd.Series(d1)

In [14]:
s3

name           bushra
father name     afsar
dtype: object

In [15]:
#q3

In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)


In [17]:
ser

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [18]:
df=pd.DataFrame(ser)

In [19]:
df.head()

0
a  0
b  1
c  2
e  3
d  4

In [20]:
ser.head()

a    0
b    1
c    2
e    3
d    4
dtype: int64

In [21]:
df=ser.to_frame().reset_index()

In [22]:
df.head(10)

index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4
5     f  5
6     g  6
7     h  7
8     i  8
9     j  9

In [23]:
#q4
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

In [24]:
ser1=pd.Series(np.arange(26))

In [25]:
df=pd.DataFrame({"col1":ser,"col2":ser1})

In [26]:
df.head()

col1  col2
0    a     0
1    b     1
2    c     2
3    d     3
4    e     4

In [27]:
df=pd.concat([ser,ser1],axis=1)

In [28]:
df.head()

0  1
0  a  0
1  b  1
2  c  2
3  d  3
4  e  4

In [29]:
#q5

In [30]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.head()

0    a
1    b
2    c
3    e
4    d
dtype: object

In [31]:
ser.name="alphabets"

In [32]:
ser.head()

0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [33]:
#q6

In [34]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1.isin(ser2)

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [35]:
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

In [36]:
#q7

In [37]:
u=pd.Series(np.union1d(ser1,ser2))

In [38]:
i=pd.Series(np.intersect1d(ser1,ser2))

In [39]:
u

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [40]:
i

0    4
1    5
dtype: int64

In [41]:
u[~u.isin(i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [42]:
import numpy as np
ser=pd.Series(np.random.normal(10,5,25))

In [43]:
ser.mean()

9.19675939728998

In [44]:
ser.median()

9.743823888776898

In [45]:
ser.min()

-0.9331984540023459

In [46]:
ser.max()

19.311506968506855

In [47]:
np.percentile(ser,q=[0,25,50,75,100])

array([-0.93319845,  4.49530815,  9.74382389, 14.00056219, 19.31150697])

In [48]:
ser1=pd.Series([1,2,3,4,5,6,7],index=list('abcdefg'))

In [49]:
np.percentile(ser1,q=[0,25,50,75,100])

array([1. , 2.5, 4. , 5.5, 7. ])

In [50]:
ser = pd.Series(np.take(list('bushraaa'), np.random.randint(8, size=30)))


In [51]:
ser

0     h
1     r
2     s
3     a
4     s
5     b
6     a
7     s
8     s
9     a
10    u
11    r
12    a
13    h
14    h
15    u
16    a
17    h
18    u
19    r
20    u
21    a
22    r
23    u
24    a
25    a
26    a
27    h
28    a
29    a
dtype: object

In [52]:
ser.value_counts()

a    11
u     5
h     5
r     4
s     4
b     1
dtype: int64

In [53]:
ser = pd.Series(np.random.randint(1, 5, [12]))
ser

0     2
1     3
2     3
3     3
4     4
5     4
6     4
7     4
8     1
9     3
10    4
11    2
dtype: int32

In [54]:
ser.value_counts()

4    5
3    4
2    2
1    1
dtype: int64

In [55]:
ser[~ser.isin(ser.value_counts().index[:2])]="OTHERS"

In [56]:
ser

0     OTHERS
1          3
2          3
3          3
4          4
5          4
6          4
7          4
8     OTHERS
9          3
10         4
11    OTHERS
dtype: object

In [57]:
ser = pd.Series(np.random.random(20))


In [58]:
ser

0     0.176631
1     0.816883
2     0.153596
3     0.609102
4     0.760455
5     0.306663
6     0.443999
7     0.716081
8     0.999887
9     0.443637
10    0.425084
11    0.354489
12    0.276246
13    0.873225
14    0.088016
15    0.782537
16    0.949806
17    0.210334
18    0.866509
19    0.418830
dtype: float64

In [59]:
# q:12

In [60]:
ser = pd.Series(np.random.randint(1, 10, 35))
ser

0     8
1     4
2     5
3     7
4     5
5     3
6     9
7     5
8     6
9     9
10    9
11    1
12    9
13    5
14    2
15    8
16    7
17    2
18    7
19    6
20    1
21    7
22    9
23    4
24    4
25    7
26    7
27    1
28    4
29    5
30    2
31    5
32    7
33    2
34    9
dtype: int32

In [61]:
len(np.random.randint(1,10,35))

35

In [62]:
df=pd.DataFrame(ser.values.reshape(7,5))

In [63]:
df

0  1  2  3  4
0  8  4  5  7  5
1  3  9  5  6  9
2  9  1  9  5  2
3  8  7  2  7  6
4  1  7  9  4  4
5  7  7  1  4  5
6  2  5  7  2  9

In [64]:
ser.values.reshape(7,5)

array([[8, 4, 5, 7, 5],
       [3, 9, 5, 6, 9],
       [9, 1, 9, 5, 2],
       [8, 7, 2, 7, 6],
       [1, 7, 9, 4, 4],
       [7, 7, 1, 4, 5],
       [2, 5, 7, 2, 9]])

In [65]:
ser.index

RangeIndex(start=0, stop=35, step=1)

# Chapter 5

In [66]:
import pandas as pd


In [67]:
s1=pd.Series([11,22,33,44,55])

In [68]:
s1

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [69]:
s1.values

array([11, 22, 33, 44, 55], dtype=int64)

In [70]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [71]:
s2=pd.Series((12,23,45,3,1,28),index=["a","b","c","d","e","f"])

In [72]:
s2

a    12
b    23
c    45
d     3
e     1
f    28
dtype: int64

In [73]:
s2["c"]

45

In [74]:
s2["c"]=34

In [75]:
s2

a    12
b    23
c    34
d     3
e     1
f    28
dtype: int64

In [76]:
s2[s2>15]

b    23
c    34
f    28
dtype: int64

In [77]:
s2[s2<15]

a    12
d     3
e     1
dtype: int64

In [78]:
s1.name="numbers"

In [79]:
s1

0    11
1    22
2    33
3    44
4    55
Name: numbers, dtype: int64

In [80]:
dic={
    "name":"bushra",
    "city":"Karachi",
    "age":22,
    "education":"b.com"
}

In [81]:
s3=pd.Series(dic)

In [82]:
s3

name          bushra
city         Karachi
age               22
education      b.com
dtype: object

In [83]:
s3.name="Biodata"

In [84]:
s3

name          bushra
city         Karachi
age               22
education      b.com
Name: Biodata, dtype: object

In [85]:
import numpy as np
s4=pd.Series(np.arange(24),index=list("abcdefghijklmnopqrstuvwx"))

In [86]:
s4.head()

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [87]:
"e" in s4

True

In [88]:
"z" in s4

False

In [89]:
indexs=["name","city","education","fathername"]

In [90]:
s5=pd.Series(dic,index=indexs)

In [91]:
s5

name           bushra
city          Karachi
education       b.com
fathername        NaN
dtype: object

In [92]:
s5.isnull()

name          False
city          False
education     False
fathername     True
dtype: bool

In [93]:
s5[s5.isnull()]="Afsar ali"

In [94]:
s5

name             bushra
city            Karachi
education         b.com
fathername    Afsar ali
dtype: object

In [95]:
s5.isnull()

name          False
city          False
education     False
fathername    False
dtype: bool

In [96]:
s5.index

Index(['name', 'city', 'education', 'fathername'], dtype='object')

In [97]:
s5.index.name="index"

In [98]:
s5

index
name             bushra
city            Karachi
education         b.com
fathername    Afsar ali
dtype: object

In [99]:
s5.index=["a","b","c","d"]

In [100]:
s5

a       bushra
b      Karachi
c        b.com
d    Afsar ali
dtype: object

# DataFrame

In [101]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],     
        'year': [2000, 2001, 2002, 2001, 2002, 2003],      
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 
frame = pd.DataFrame(data) 

In [102]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [103]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [104]:
frame1=pd.DataFrame(frame,columns=['year','state','pop'])

In [105]:
frame1

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [106]:
frame2=pd.DataFrame(frame1,columns=["year","pop","state","town"],index=["one","two","three","four","five","six"])

In [107]:
frame2

year  pop state  town
one     NaN  NaN   NaN   NaN
two     NaN  NaN   NaN   NaN
three   NaN  NaN   NaN   NaN
four    NaN  NaN   NaN   NaN
five    NaN  NaN   NaN   NaN
six     NaN  NaN   NaN   NaN

In [108]:
frame2.index.name="index"

In [109]:
frame2

year  pop state  town
index                       
one     NaN  NaN   NaN   NaN
two     NaN  NaN   NaN   NaN
three   NaN  NaN   NaN   NaN
four    NaN  NaN   NaN   NaN
five    NaN  NaN   NaN   NaN
six     NaN  NaN   NaN   NaN

In [110]:
frame2.columns

Index(['year', 'pop', 'state', 'town'], dtype='object')

In [111]:
frame2.year

index
one     NaN
two     NaN
three   NaN
four    NaN
five    NaN
six     NaN
Name: year, dtype: float64

In [112]:
frame1.columns

Index(['year', 'state', 'pop'], dtype='object')

In [113]:
frame1

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [114]:
frame1.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [115]:
frame1["pop"]

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [116]:
frame1["town"]=np.arange(6)

In [117]:
frame1

year   state  pop  town
0  2000    Ohio  1.5     0
1  2001    Ohio  1.7     1
2  2002    Ohio  3.6     2
3  2001  Nevada  2.4     3
4  2002  Nevada  2.9     4
5  2003  Nevada  3.2     5

In [118]:
frame1+frame2

pop state  town  year
0      NaN   NaN   NaN   NaN
1      NaN   NaN   NaN   NaN
2      NaN   NaN   NaN   NaN
3      NaN   NaN   NaN   NaN
4      NaN   NaN   NaN   NaN
5      NaN   NaN   NaN   NaN
five   NaN   NaN   NaN   NaN
four   NaN   NaN   NaN   NaN
one    NaN   NaN   NaN   NaN
six    NaN   NaN   NaN   NaN
three  NaN   NaN   NaN   NaN
two    NaN   NaN   NaN   NaN

In [119]:
frame1+frame1

year         state  pop  town
0  4000      OhioOhio  3.0     0
1  4002      OhioOhio  3.4     2
2  4004      OhioOhio  7.2     4
3  4002  NevadaNevada  4.8     6
4  4004  NevadaNevada  5.8     8
5  4006  NevadaNevada  6.4    10

In [120]:
frame1

year   state  pop  town
0  2000    Ohio  1.5     0
1  2001    Ohio  1.7     1
2  2002    Ohio  3.6     2
3  2001  Nevada  2.4     3
4  2002  Nevada  2.9     4
5  2003  Nevada  3.2     5

In [121]:
val=pd.Series([11,33,453,23],index=[1,5,2,0])

In [122]:
frame1["debt"]=val

In [123]:
frame1

year   state  pop  town   debt
0  2000    Ohio  1.5     0   23.0
1  2001    Ohio  1.7     1   11.0
2  2002    Ohio  3.6     2  453.0
3  2001  Nevada  2.4     3    NaN
4  2002  Nevada  2.9     4    NaN
5  2003  Nevada  3.2     5   33.0

In [124]:
frame1["abc"]=frame1.state=='Ohio'

In [125]:
frame1

year   state  pop  town   debt    abc
0  2000    Ohio  1.5     0   23.0   True
1  2001    Ohio  1.7     1   11.0   True
2  2002    Ohio  3.6     2  453.0   True
3  2001  Nevada  2.4     3    NaN  False
4  2002  Nevada  2.9     4    NaN  False
5  2003  Nevada  3.2     5   33.0  False

In [126]:
del frame1["abc"]

In [127]:
frame1

year   state  pop  town   debt
0  2000    Ohio  1.5     0   23.0
1  2001    Ohio  1.7     1   11.0
2  2002    Ohio  3.6     2  453.0
3  2001  Nevada  2.4     3    NaN
4  2002  Nevada  2.9     4    NaN
5  2003  Nevada  3.2     5   33.0

In [128]:
 pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 
        'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}} 
frame3=pd.DataFrame(pop)

In [129]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [130]:
# dataframe.colname 
# del dataframe.colname 
# we cannot create or del column by this syntax

In [131]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [132]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [133]:
frame2

year  pop state  town
index                       
one     NaN  NaN   NaN   NaN
two     NaN  NaN   NaN   NaN
three   NaN  NaN   NaN   NaN
four    NaN  NaN   NaN   NaN
five    NaN  NaN   NaN   NaN
six     NaN  NaN   NaN   NaN

In [134]:
frame3.index.name="year"

In [135]:
frame3.columns.name="columns"

In [136]:
frame3

columns  Nevada  Ohio
year                 
2000        NaN   1.5
2001        2.4   1.7
2002        2.9   3.6

# Index object

In [137]:
s1=pd.Series(np.arange(4),index=['a','b','c','d'])

In [138]:
index=s1.index

In [139]:
index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [140]:
index[0]

'a'

In [141]:
index[0]='e'

TypeError: Index does not support mutable operations

In [ ]:
# we cannot alter the value of index

In [ ]:
s1=pd.Series([1,2,3,21,4,3],index=list("aabbcc"))

In [ ]:
# wwe can use duplicate labels/index in pandas


In [ ]:
s1

# Reindexing

In [ ]:
s1=pd.Series(np.arange(6),index=list('abcdef'))

In [ ]:
s1

In [ ]:
s1.reindex(["b","c","d","a","f","e","g"])

In [ ]:
s1.reindex(["b","c","d","a","f","e","g"],method="ffill")

In [ ]:
s1.reindex(["b","c","d","a","f","e","g"],method="bfill")

In [ ]:
 frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                      index=['a', 'c', 'd'],
                      columns=['Ohio', 'Texas', 'California'])
frame

In [ ]:
frame=frame.reindex(index=["c","a","d","e"],columns=["California","Ohio","Texas","Indiana"])

# Dropping Entries from an Axis 

In [ ]:
 obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])


In [ ]:
obj

In [ ]:
obj.drop("a")

In [ ]:
obj.drop(["b","c"])

In [ ]:
# DataFrame

In [ ]:
 data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                     index=['Ohio', 'Colorado', 'Utah', 'New York'],
                     columns=['one', 'two', 'three', 'four'])


In [ ]:
data

In [ ]:
data.drop(["one","two"],axis=1)# we can del values by col by providing axis

In [ ]:
data.drop("Ohio",inplace=True)

In [ ]:
data

# Indexing, Selection, and Filtering 

In [ ]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])


In [ ]:
obj

In [ ]:
obj["a"]

In [ ]:
obj[["a","c"]]

In [ ]:
obj[1]

In [ ]:
obj[[1,3,0]]

In [ ]:
obj["a":"c"]

In [ ]:
obj[:2]

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])


In [ ]:
data


In [ ]:
data["one"]

In [ ]:
data[["one","two"]]

In [ ]:
a=data[:2]=11

In [ ]:
data

In [ ]:
a

In [ ]:
data[data['three'] > 10] 

In [ ]:
data[data<10]=167

In [ ]:
data

In [ ]:
# we can do indexing by three ways :
# first by label sec by index and third by condition(boolean indexing)

# Selection with loc and iloc

In [2]:
 data.loc['Colorado', ['two', 'three']] 

NameError: name 'data' is not defined

In [ ]:
data

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])


In [ ]:
data

In [ ]:
data.loc["Utah"]

In [ ]:
data.loc["Ohio",["one","two"]]

In [ ]:
data.iloc[0]

In [ ]:
data.iloc[1,[1,0,2]]

In [ ]:
# by iloc and loc we can select subset of row and column

In [ ]:
data.iloc[[1, 2], [3, 0, 1]] 

In [ ]:
data

In [ ]:
data.loc[:'Utah',"two"]

In [ ]:
s1=pd.Series(np.arange(5),index=list('abcde'))

In [ ]:
s2=pd.Series(np.arange(6,11),index=list("abdef"))

In [ ]:
s1+s2

In [ ]:
# if we add two series and there is index which are not common there then output will be nan

# Arithmetic methods with fill values 

In [ ]:
 df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                    columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                             columns=list('abcde'))


In [ ]:
df2.loc[1,"b"]=np.nan

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1+df2

In [ ]:
df1.add(df2,fill_value=0)

In [ ]:
# by passing fill_value parameter we can chnge nan to any float no. by default it is none 

In [ ]:
# while reindexing we can also give fill_value

In [ ]:
 frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                      columns=list('bde'), 
                      index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [ ]:
frame

In [ ]:
frame.iloc[0]

In [ ]:
s1=frame.iloc[0]

In [ ]:
frame-s1

In [ ]:
# if we can sub and sub series  & dataframe if they both have same index and col name while if there is not common index then it will provide nan

In [ ]:
frame+s1

# Function Application and Mapping

In [ ]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [ ]:
abs(frame)

In [ ]:
a=lambda x : x.max()-x.min()
frame.apply(a)

In [ ]:
# by apply func we can use operation in row wise

In [ ]:
frame.apply(a,axis=1)

In [ ]:
# if we provide axis=1 we can also apply fuction col wise 
# apply fuction work on 1d array

In [ ]:
# we can use applymap fuction for formatting apply map works element wise

In [ ]:
formt=lambda x:"%.2f" % x
frame.applymap(formt)

In [ ]:
a=frame["b"]

In [ ]:
a.map(formt)

In [ ]:
# map is used in series

# Sorting and Ranking 

In [ ]:
obj=pd.Series([1,2,44,5,6],index=list('abdbe'))

In [ ]:
obj

In [ ]:
obj.sort_index()

In [ ]:
obj

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), 
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])


In [ ]:
frame

In [ ]:
frame.sort_index()

In [ ]:
frame.sort_index(axis=1)

In [ ]:
frame.sort_index(ascending=False)

In [ ]:
frame.sort_index(axis=1,ascending=False)

In [ ]:
obj

In [ ]:
obj.sort_values()

In [ ]:
# we can also do sorting by values in series by using sort_value method

In [ ]:
 frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})


In [ ]:
frame

In [ ]:
frame.sort_values(by="b")# by using "by" argument we can gibe specific col name according which sorting is done

In [ ]:
frame.sort_values(by=["a","b"])

In [ ]:
frame.sort_values(by=["b","a"])

In [ ]:
# by providing two col  name sorting is done acc to first col 

# Ranking

In [ ]:
s1=pd.Series([2,5,3,2,13,53])

In [ ]:
s1.rank()

In [ ]:
s1

In [ ]:
s1.rank(ascending=False)

In [ ]:
# while ranking if the values are same then it will give average

In [ ]:
s1.rank(ascending=False,method="first")

In [ ]:
s1.rank(ascending=False,method="min")

In [ ]:
s1.rank(ascending=False,method="max")

In [ ]:
s1.rank(ascending=False,method="dense")

In [ ]:
# dense is same as min

In [ ]:
# min give lowest rank and max give highest rank to both similar value

In [142]:
import pandas as pd

In [143]:
import numpy as np

In [144]:
 df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                    [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'],
                   columns=['one', 'two'])


In [145]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [146]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [151]:
# it will return col sum 
df.sum(skipna=False)

one   NaN
two   NaN
dtype: float64

In [152]:
df.sum(axis=1,skipna=False)

a     NaN
b    2.60
c     NaN
d   -0.55
dtype: float64

In [149]:
# it will return row wise sum

In [153]:
# skipna igonore nan 

In [156]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [157]:
# idmin and idmax give index of max and min of df

In [158]:
df.cumsum(axis=1)

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [160]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [161]:
df.count()

one    3
two    2
dtype: int64

In [162]:
# count no. of values exist except nan in col

# Correlation and Covariance 

In [6]:
import pandas_datareader.data as web 

In [7]:
data={key:web.get_data_yahoo(key)
     for key in['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [8]:
price=pd.DataFrame({key:data["Volume"]
                  for key,data in data.items()})

NameError: name 'pd' is not defined

In [ ]:
price=pd.DataFrame({key:data["Adj Close"]
                  for key,data in data.items()})

In [ ]:
price.head()

In [ ]:
import pandas as pd
returns=price.pct_change()

In [ ]:
returns.tail()